### ISSUE TITLE
Typo error in Readme.md

### ISSUE THREAD

**Issue by Debanitrkl** [sanderlab/CellBox#14]
```
jovyan@jupyter-dfci-2dcellbox-2d7985pt7y:~$ python scripts/main.py -config=configs/Example.random_partition.json
WARNING: Logging before flag parsing goes to stderr.
W0206 06:36:49.652899 139714245154624 __init__.py:329] Limited tf.compat.v2.summary API due to missing TensorBoard installation.

        version 0.0.2
        -- Jan 20, 2019 --
        * Huge Bug fixed with gradually increasing nT
        * Reorganize utils.py

        version 0.0.3
        -- Jan 21, 2019 --
        * Adding test of convergece

        version 0.0.3.1
        -- Jan 23, 2019 --
        * Roll back to x_0 = 1

        version 0.0.3
        -- Jan 21, 2019 --
        * Roll back 0.0.3

        version 0.0.3.2
        -- Jan 26, 2019 --
        * Adding outputs for test_convergence()

        version 0.0.3.3
        -- Jan 30, 2019 --
        * use last 20 time step for test_convergence()

        version 0.0.3.4
        -- Jan 31, 2019 --
        * use 0.1 as initial values for alpha and eps variable

        version 0.0.4
        -- Feb 11, 2019 --
        * Roll back 0.0.3.3
        * Add constraints on direct regulation from drug nodes to phenotypic nodes

        version 0.0.5
        -- Feb 21, 2019 --
        * Add function to normalize mse loss to different nodes.

        version 0.1.0
        -- Aug 21, 2019 --
        * Re-structure codes for publish.

        version 0.1.1
        -- Oct 4, 2019 --
        * Add new kinetics
        * Add new ODE solvers
        * Add new envelop forms

        version 0.2.0
        -- Feb 26, 2020 --
        * Add support of matrix operation rather than function mapping
        * Roughly 5x faster

        version 0.2.1
        -- Apr 5, 2020 --
        * Reformat for better code style
        * Revise docs

        version 0.2.2
        -- Apr 23, 2020 --
        * Add support to tf.Datasets
        * Add support to tf.sparse
        * Prepare for sparse single-cell data

        version 0.2.3
        -- June 8, 2020 --
        * Add support to L2 loss (alone or together with L1, i.e. elastic net)
        * Clean the example configs folder


Traceback (most recent call last):
  File "scripts/main.py", line 64, in <module>
    cfg = pertbio.config.Config(master_args.experiment_config_path)
  File "/srv/conda/envs/notebook/lib/python3.6/site-packages/pertbio/config.py", line 12, in __init__
    with open(config_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/Example.random_partition.json'
```

> Error in `python scripts/main.py -config=configs/Example.random_partition.json`

> Suggested change: ` python scripts/main.py -config=configs/example.random_partition.json`

**Comment by Debanitrkl** [comment]
#15

**Comment by DesmondYuan** [comment]
Thanks for pointing that out! I just approved the PR.
